[project]
name = "price-mcp"
version = "0.1.0"
description = "Amazon price search server using MCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "requests>=2.32.3",
    "python-dotenv>=1.0.0",
]
